//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 投票系统.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class groups
    {
        public groups()
        {
            this.users = new HashSet<users>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Privilege { get; set; }
        public string GroupName { get; set; }
    
        public virtual privilege privilege1 { get; set; }
        public virtual ICollection<users> users { get; set; }
    }
}
