//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 投票系统.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ktpf
    {
        public int ID { get; set; }
        public int productId { get; set; }
        public int memberId { get; set; }
        public Nullable<int> jssp { get; set; }
        public Nullable<int> jsnd { get; set; }
        public Nullable<int> jjxy { get; set; }
        public Nullable<int> zscq { get; set; }
        public Nullable<int> shxy { get; set; }
        public Nullable<int> tgyy { get; set; }
        public Nullable<int> dfhj { get; set; }
    
        public virtual product product { get; set; }
        public virtual users users { get; set; }
    }
}
