//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 投票系统.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class privilege
    {
        public privilege()
        {
            this.groups = new HashSet<groups>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> AddReview { get; set; }
        public Nullable<int> Review { get; set; }
        public Nullable<int> Administrator { get; set; }
        public Nullable<int> Technical { get; set; }
        public Nullable<int> TJ { get; set; }
        public Nullable<int> ZG { get; set; }
    
        public virtual ICollection<groups> groups { get; set; }
    }
}
