//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 投票系统.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.upjd = new HashSet<upjd>();
            this.tpfs = new HashSet<tpfs>();
            this.ktpf = new HashSet<ktpf>();
            this.pjtj = new HashSet<pjtj>();
            this.tp = new HashSet<tp>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string userName { get; set; }
        public string Category { get; set; }
        public string Groups { get; set; }
        public string FZR { get; set; }
        public string filepath { get; set; }
        public Nullable<System.DateTime> addDate { get; set; }
        public string state { get; set; }
        public string TJDJ { get; set; }
        public string QRDJ { get; set; }
        public string BH { get; set; }
    
        public virtual ICollection<upjd> upjd { get; set; }
        public virtual ICollection<tpfs> tpfs { get; set; }
        public virtual ICollection<ktpf> ktpf { get; set; }
        public virtual ICollection<pjtj> pjtj { get; set; }
        public virtual ICollection<tp> tp { get; set; }
    }
}
