//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 投票系统.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class productjd
    {
        public productjd()
        {
            this.tj = new HashSet<tj>();
            this.tpfs = new HashSet<tpfs>();
            this.confirm = new HashSet<confirm>();
            this.pjtj = new HashSet<pjtj>();
        }
    
        public int ID { get; set; }
        public string YEAR { get; set; }
        public string State { get; set; }
        public string NextState { get; set; }
    
        public virtual ICollection<tj> tj { get; set; }
        public virtual ICollection<tpfs> tpfs { get; set; }
        public virtual ICollection<confirm> confirm { get; set; }
        public virtual ICollection<pjtj> pjtj { get; set; }
    }
}
