//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 投票系统.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.tj = new HashSet<tj>();
            this.tpfs = new HashSet<tpfs>();
            this.ktpf = new HashSet<ktpf>();
            this.pjtj = new HashSet<pjtj>();
            this.tp = new HashSet<tp>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public Nullable<int> Group { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Professional { get; set; }
        public string Source { get; set; }
        public string Department { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> RegionDate { get; set; }
        public string Remark { get; set; }
    
        public virtual groups groups { get; set; }
        public virtual ICollection<tj> tj { get; set; }
        public virtual ICollection<tpfs> tpfs { get; set; }
        public virtual ICollection<ktpf> ktpf { get; set; }
        public virtual ICollection<pjtj> pjtj { get; set; }
        public virtual ICollection<tp> tp { get; set; }
    }
}
