//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.upjd = new HashSet<upjd>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string userName { get; set; }
        public string Category { get; set; }
        public string Groups { get; set; }
        public string FZR { get; set; }
        public string filepath { get; set; }
        public Nullable<System.DateTime> addDate { get; set; }
        public string state { get; set; }
    
        public virtual ICollection<upjd> upjd { get; set; }
    }
}
