//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public Nullable<int> Group { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Professional { get; set; }
        public string Source { get; set; }
        public string Department { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> RegionDate { get; set; }
        public string Remark { get; set; }
    
        public virtual groups groups { get; set; }
    }
}
